### ISSUE TITLE
Add renBTC icon

### ISSUE THREAD

**Issue by vbstreetz** [Synthetixio/synthetix-assets#11]
Similar to:

![](https://assets.coingecko.com/coins/images/11370/small/renBTC.png?1589985711)

To be used in loans section

**Comment by vbstreetz** [comment]
Hey @evgenyboxer. Where do we get the new token icons?

**Comment by evgenyboxer** [comment]
Hey, @vbstreetz please ping @zoe-archer, she will create one for you!

**Comment by vbstreetz** [comment]
@zoe-archer ping

**Comment by andytcf** [comment]
@vbstreetz since renBTC is not a synth we don't add it here under the /assets repo. You can reference it separately within the staking dApp
